-- Phase 5, step 3 (docs/16): cancelling, the expiry sweep, extensions and
-- automatic reminders. Columns generated by `prisma migrate diff`; the checks
-- and the constraint rewrite below are hand-written.

-- AlterTable
ALTER TABLE "Envelope" ADD COLUMN     "expiredAt" TIMESTAMP(3),
ADD COLUMN     "reminderIntervalDays" INTEGER,
ADD COLUMN     "voidReason" TEXT,
ADD COLUMN     "voidedAt" TIMESTAMP(3),
ADD COLUMN     "voidedByUserId" UUID;

-- AlterTable
ALTER TABLE "Recipient" ADD COLUMN     "expiryWarnedAt" TIMESTAMP(3),
ADD COLUMN     "lastSeenAt" TIMESTAMP(3),
ADD COLUMN     "moreTimeRequestedAt" TIMESTAMP(3);

-- CreateIndex
CREATE INDEX "Envelope_status_expiresAt_idx" ON "Envelope"("status", "expiresAt");

-- AddForeignKey
ALTER TABLE "Envelope" ADD CONSTRAINT "Envelope_voidedByUserId_fkey" FOREIGN KEY ("voidedByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- A discarded draft was never sent, so VOIDED joins DRAFT as a status that may
-- have no sentAt.
ALTER TABLE "Envelope" DROP CONSTRAINT "Envelope_sent_has_time";
ALTER TABLE "Envelope"
  ADD CONSTRAINT "Envelope_sent_has_time"
    CHECK ("status" IN ('DRAFT', 'VOIDED') OR "sentAt" IS NOT NULL),
  ADD CONSTRAINT "Envelope_voided_has_time"
    CHECK ("status" <> 'VOIDED' OR "voidedAt" IS NOT NULL),
  -- Cancelling a sent envelope needs a reason; discarding a draft does not.
  ADD CONSTRAINT "Envelope_voided_sent_has_reason"
    CHECK ("status" <> 'VOIDED' OR "sentAt" IS NULL OR "voidReason" IS NOT NULL),
  ADD CONSTRAINT "Envelope_expired_has_time"
    CHECK ("status" <> 'EXPIRED' OR "expiredAt" IS NOT NULL),
  ADD CONSTRAINT "Envelope_reminder_interval_range"
    CHECK ("reminderIntervalDays" IS NULL OR "reminderIntervalDays" BETWEEN 1 AND 30);
