import type { Readable } from 'node:stream';

export interface StoredObject {
  body: Readable;
  contentLength?: number;
  contentType?: string;
}

/**
 * Object storage for documents. Keys are always generated by the application
 * (never user-supplied filenames, docs/10). Implemented by S3StorageService.
 */
export abstract class StorageService {
  abstract readonly bucket: string;
  abstract put(
    key: string,
    body: Buffer,
    options: { contentType: string; metadata?: Record<string, string> },
  ): Promise<void>;
  abstract get(key: string): Promise<StoredObject>;
  abstract delete(key: string): Promise<void>;
  /** Cheap reachability check for /health. */
  abstract ping(): Promise<void>;
}

export function envelopeDocumentKey(
  tenantId: string,
  envelopeId: string,
  versionNumber: number,
  uniqueId: string,
): string {
  return `tenants/${tenantId}/envelopes/${envelopeId}/v${versionNumber}-${uniqueId}.pdf`;
}
