-- Phase 4, step 6: private download links for finished documents too large to
-- attach to the completion email. Generated by `prisma migrate diff`.
-- CreateTable
CREATE TABLE "CompletionDownload" (
    "id" UUID NOT NULL,
    "envelopeId" UUID NOT NULL,
    "recipientId" UUID,
    "tokenHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "downloadCount" INTEGER NOT NULL DEFAULT 0,
    "lastDownloadedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CompletionDownload_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "CompletionDownload_tokenHash_key" ON "CompletionDownload"("tokenHash");

-- CreateIndex
CREATE INDEX "CompletionDownload_envelopeId_idx" ON "CompletionDownload"("envelopeId");

-- AddForeignKey
ALTER TABLE "CompletionDownload" ADD CONSTRAINT "CompletionDownload_envelopeId_fkey" FOREIGN KEY ("envelopeId") REFERENCES "Envelope"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CompletionDownload" ADD CONSTRAINT "CompletionDownload_recipientId_fkey" FOREIGN KEY ("recipientId") REFERENCES "Recipient"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- The runtime role gets this table through the default privileges set in the
-- initial migration, so no GRANT is needed.
